### ISSUE TITLE
<script cml-type="json" /> 应该不是必须项？

### ISSUE THREAD

**Issue by js-newbee** [beatles-chameleon/beatles-chameleon.github.io#1]
<script cml-type="json" /> 应该不是必须项，例如 page/component 没有额外引入其他组件，也没有自定义标题啥的，此时再去写 <script cml-type="json" /> 有些多余。

建议如果没有写 <script cml-type="json" /> 时，就按 <script cml-type="json">{}</script> 来处理了？

**Comment by beatles-chameleon** [comment]
非常感谢你的建议，这个问题提的很好，我们内部也讨论过这个问题，json是否是必须项，我们会继续收集反馈，决定是否进行调整。

**Comment by beatles-chameleon** [comment]
> <script cml-type="json" /> 应该不是必须项，例如 page/component 没有额外引入其他组件，也没有自定义标题啥的，此时再去写 <script cml-type="json" /> 有些多余。 建议如果没有写 <script cml-type="json" /> 时，就按 <script cml-type="json">{}</script> 来处理了？

非常感谢你的建议，这个问题提的很好，我们内部也讨论过这个问题，json是否是必须项，我们会继续收集反馈，决定是否进行调整。
