### ISSUE TITLE
https://cmljs.org/doc/example/poly.html?h=path.res

### ISSUE THREAD

**Issue by phan-pivotal** [beatles-chameleon/beatles-chameleon.github.io#3]
建议最好提示要与配合使用，避免”小白“落坑。
var path= require("path");

excludeBablePath: [
  path.resolve(__dirname, "./src/components/echart/ec-echart")
];

**Comment by phan-pivotal** [comment]
且中间这句应更新为：

path.resolve(__dirname, "./src/components/echart/ec-canvas")

**Comment by beatles-chameleon** [comment]
感谢反馈，已更正：https://cml.js.org/doc/example/poly.html
